Refactored Display implementation for Platform enum
OxyDeadbeef/whoami pull request #83
Opened 2024-01-23 11:32 UTC by sebihutanu1

## WHOAMI

### Key Changes:
1. **Display Restructuring:**
   - Significantly restructured the Display implementation for the Platform type.
   - Introduced a dedicated file, `disp.rs`, to centralize and streamline platform-specific display functions.

2. **Aesthetic Enhancements:**
   - Revamped the platform display, focusing on enhancing the overall aesthetic.
   - Resulting in a more visually appealing output for improved user experience.
   ##
   To enhance the utility's adaptability, a crucial implementation has been added. The program checks whether it is running in a terminal environment (using https://crates.io/crates/is-terminal) before deciding how to display the platform. If executed in a terminal, the graphical version is presented; otherwise, in scenarios like running in a pipe, the text version is displayed.

2024-01-23 11:35 UTC, alexandruradovici requested changes
Please run `cargo fmt` to format your source.

2024-01-23 12:34 UTC, alexandruradovici requested changes
Please fix `clippy`s errors.

2024-01-23 13:38 UTC, alexandruradovici requested changes

2024-01-23 13:38 UTC, alexandruradovici commented on src/fake.rs
> -//! Currently used for WebAssembly unknown (non-web) only
Why delete this?

2024-01-23 13:38 UTC, alexandruradovici commented on src/fake.rs
Please explain why do we need this file?

2024-01-23 13:48 UTC, sebihutanu1 commented on src/fake.rs
> -//! Currently used for WebAssembly unknown (non-web) only
by mistake, will fix

2024-01-23 17:03 UTC, sebihutanu1 commented on src/fake.rs
I am sorry, I just noticed that I somehow copied the entire code from lib.rs to fake.rs. . I'm not sure how that happened, but I'll fix it immediately.

2024-01-24 05:31 UTC, AldaronLau reviewed
Is there a reason that this has to exist within the whoami crate?  I feel like this functionality could be split out into its own crate depending on whoami.

2024-02-14 06:50 UTC, AldaronLau commented
@sebihutanu1 I'm going to close this PR, as I have decided it's functionality doesn't belong in the whoami crate.  I recommend creating a separate crate for it, depending on whoami and is-terminal, if you require this functionality.

If you'd like to contribute to this project in another way, feel free to send me an email at <aldaronlau@gmail.com> or comment in #89, and we can figure something out.  Thank you for your interest.

2024-02-14 06:50 UTC, closed without merging